plugins
{
	id 'fabric-loom' version '1.9-SNAPSHOT'
}

version = project.mod_version
group = project.maven_group

base
{
	archivesName = "${project.archives_base_name}-FABRIC-${project.minecraft_version}"
}

repositories
{
	maven { url = 'https://maven.parchmentmc.org/' }
	maven { url = 'https://jitpack.io'}
	maven { url = "https://maven.terraformersmc.com/"}
	maven { url = 'https://maven.ladysnake.org/releases'}
}

dependencies
{
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered()
	{
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${project.mappings_version}@zip")
	}

	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	modApi("com.github.Virtuoel:Pehkui:${pehkui_version}", {
		exclude group: "net.fabricmc.fabric-api"
	})
	modImplementation "dev.emi:trinkets:${trinkets_version}"

	modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cca_version}"
	include "dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cca_version}"

	//implementation 'io.github.onyxstudios:Cardinal-Components-API:3.1.1'
	//modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-base:${cardinal_version}"
	//modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-base:3.1.1"

}

processResources
{
	inputs.property "version", project.version
	filesMatching("fabric.mod.json") { expand "version": project.version }
}

tasks.withType(JavaCompile).configureEach { it.options.release = 17 }

java
{
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}